//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisiselWebProjesi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnaSayfas
    {
        public int id { get; set; }
        public string menugorsel { get; set; }
        public string menu1 { get; set; }
        public string menu2 { get; set; }
        public string menu3 { get; set; }
        public string menu4 { get; set; }
        public string marka { get; set; }
        public string hosgeldin { get; set; }
        public string bilgi { get; set; }
        public string about { get; set; }
        public string ourstory1 { get; set; }
        public string paragraf1 { get; set; }
        public string gorselfirca { get; set; }
        public string photo1 { get; set; }
        public string photo2 { get; set; }
        public string photo3 { get; set; }
        public string photo4 { get; set; }
        public string photo5 { get; set; }
        public string photo6 { get; set; }
        public string photo7 { get; set; }
        public string photo8 { get; set; }
        public string discover { get; set; }
        public string ourstory2 { get; set; }
        public string paragraf2 { get; set; }
        public string gorselsim { get; set; }
        public string contact { get; set; }
        public string aboutus { get; set; }
        public string phone { get; set; }
        public string location { get; set; }
        public string mail { get; set; }
        public string paragraf3 { get; set; }
        public string isim { get; set; }
    }
}
